# Generated by Django 4.2 on 2024-01-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menus'},
        ),
    ]
